import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

apply plugin: 'org.jetbrains.kotlin.jvm'
apply plugin: 'java-library'
apply plugin: 'ru.vyarus.animalsniffer' // 添加回原来有的animalsniffer插件

// 代码源设置：将commonMain和jvmMain的源码合并到一起
sourceSets {
  main {
    kotlin {
      srcDirs += ['src/commonMain/kotlin', 'src/jvmMain/kotlin'] 
    }
  }
  test {
    kotlin {
      srcDirs += ['src/commonTest/kotlin', 'src/jvmTest/kotlin']
    }
  }
}

compileKotlin {
  kotlinOptions {
    freeCompilerArgs += "-Xuse-experimental=kotlinx.coroutines.ExperimentalCoroutinesApi"
    freeCompilerArgs += "-Xexperimental=com.squareup.wire.WireGrpcExperimental"
    freeCompilerArgs += "-Xmulti-platform"
    freeCompilerArgs += "-Xopt-in=kotlin.Experimental"
  }
}

jar {
  manifest {
    attributes('Automatic-Module-Name': 'wire-runtime')
  }
}

dependencies {
  api deps.kotlin.stdlib.jdk8
  api deps.okio.jvm  // 使用JVM版本的Okio
  compileOnly deps.android
  
  testImplementation deps.assertj
  testImplementation deps.kotlin.test.junit
}

// 配置animalsniffer
animalsniffer {
  sourceSets = [sourceSets.main]
  ignore 'com.squareup.wire.internal'
}

// 配置发布
afterEvaluate {
  tasks.create('installLocally') {
    dependsOn 'publishToMavenLocal'
  }
}

// Maven发布配置
apply plugin: 'maven-publish'
publishing {
  publications {
    maven(MavenPublication) {
      artifactId = 'wire-runtime'
      from components.java
    }
  }
}
